"""Feedback loop: update edge weights based on downstream signals.

Signals arrive from three sources:

  - User: explicit correction or confirmation
  - LLM: gap-detection flag ("I needed more context")
  - Logic engine: MissingFact exception during rule evaluation

Update rule::

    w ← clip(w + α · sign · s, 0, 1)

where ``sign`` is +1 for helpful edges and −1 for noisy ones. Source
reliability is encoded in ``s``: user > logic > llm.
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from context_engine.store import GraphStore
from context_engine.types import FeedbackSignal

if TYPE_CHECKING:
    from context_engine.strategy import StrategyResolver

_SOURCE_SCALE = {"user": 1.0, "logic_engine": 0.8, "llm": 0.4}

_SIDECAR_DIR = ".ctx"
_WEIGHTS_FILE = "weights.yaml"
_SIDECAR_HEADER = "# auto-generated by the feedback loop — do not hand-edit\n"


class FeedbackApplier:
    def __init__(
        self,
        store: GraphStore,
        alpha: float = 0.15,
        strategies: StrategyResolver | None = None,
        tree_root: Path | None = None,
    ) -> None:
        self.store = store
        self.alpha = alpha
        self.strategies = strategies
        self.tree_root = tree_root

    def _write_sidecar_entry(
        self,
        source: str,
        target: str,
        edge_type: str,
        new_weight: float,
    ) -> None:
        """Persist a weight override to ``<tree_root>/.ctx/weights.yaml``.

        Creates the parent directory if missing.  The sidecar is the
        persistence layer for feedback weights; SQLite is the query-time index.
        Neither ``readme.md`` nor ``edges.yaml`` is ever modified by this path.
        """
        if self.tree_root is None:
            return
        sidecar_dir = self.tree_root / _SIDECAR_DIR
        sidecar_dir.mkdir(parents=True, exist_ok=True)
        sidecar_path = sidecar_dir / _WEIGHTS_FILE

        if sidecar_path.exists():
            raw = yaml.safe_load(sidecar_path.read_text(encoding="utf-8")) or {}
        else:
            raw = {}
        if not isinstance(raw, dict):
            raw = {}
        if not isinstance(raw.get("edges"), dict):
            raw["edges"] = {}

        key = f"{source} -> {target}:{edge_type}"
        raw["edges"][key] = {
            "weight": round(new_weight, 4),
            "updated_at": datetime.datetime.now(datetime.UTC)
            .isoformat()
            .replace("+00:00", "Z"),
            "source": "llm",
        }
        sidecar_path.write_text(
            _SIDECAR_HEADER + yaml.safe_dump(raw, sort_keys=False),
            encoding="utf-8",
        )

    def apply(self, signal: FeedbackSignal) -> dict[str, float]:
        """Apply signal and return the updated weights keyed by edge id."""
        scale = _SOURCE_SCALE.get(signal.source, 0.3)
        step = self.alpha * scale * signal.delta
        updates: dict[str, float] = {}

        for edge_id in signal.helpful_edge_ids:
            edge = self.store.get_edge(edge_id)
            if edge is None:
                continue
            new_w = _clip(edge.weight + step)
            self.store.update_edge_weight(edge_id, new_w)
            updates[edge_id] = new_w
            self._write_sidecar_entry(edge.source, edge.target, edge.type, new_w)

        for edge_id in signal.noisy_edge_ids:
            edge = self.store.get_edge(edge_id)
            if edge is None:
                continue
            new_w = _clip(edge.weight - step)
            self.store.update_edge_weight(edge_id, new_w)
            updates[edge_id] = new_w
            self._write_sidecar_entry(edge.source, edge.target, edge.type, new_w)

        # Bootstrap missing edges: when the LLM or logic engine flags nodes
        # that *should* have been in the slice, create weak edges from any
        # used node to them. These edges strengthen over time if they prove
        # useful.
        for used in signal.used_node_ids:
            for missing in signal.missing_node_ids:
                if used == missing:
                    continue
                edge = self.store.upsert_edge(
                    source=used,
                    target=missing,
                    edge_type="learned",
                    weight=0.35,
                    content="inferred from feedback signal",
                )
                updates[edge.id] = edge.weight

        # Propagate the signal to the strategy resolver when available.
        if self.strategies is not None and signal.query_tuple is not None:
            helpful_types = [
                e.type
                for eid in signal.helpful_edge_ids
                if (e := self.store.get_edge(eid)) is not None
            ]
            noisy_types = [
                e.type
                for eid in signal.noisy_edge_ids
                if (e := self.store.get_edge(eid)) is not None
            ]
            if len(helpful_types) >= len(noisy_types):
                self.strategies.record_success(signal.query_tuple, helpful_types, noisy_types)
            else:
                self.strategies.record_failure(signal.query_tuple, helpful_types, noisy_types)

        return updates


def _clip(value: float) -> float:
    return max(0.0, min(1.0, value))
